# Generated by Django 3.1.1 on 2020-09-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image', models.ImageField(blank=True, default='defalt.png', upload_to='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('type_product', models.CharField(choices=[('Hamburguer', 'Hamburguer'), ('Bebidas', 'Bebidas'), ('Pasteis', 'Pasteis'), ('Outros', 'Outros')], default='Hamburguer', max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
